export const calendarId = {
  "AF Afghanistan": "en.af#holiday@group.v.calendar.google.com",
  "AL Albania": "en.al#holiday@group.v.calendar.google.com",
  "DZ Algeria": "en.dz#holiday@group.v.calendar.google.com",
  "AS American Samoa": "en.as#holiday@group.v.calendar.google.com",
  "AD Andorra": "en.ad#holiday@group.v.calendar.google.com",
  "AO Angola": "en.ao#holiday@group.v.calendar.google.com",
  "AI Anguilla": "en.ai#holiday@group.v.calendar.google.com",
  "AG Antigua and Barbuda": "en.ag#holiday@group.v.calendar.google.com",
  "AR Argentina": "en.ar#holiday@group.v.calendar.google.com",
  "AM Armenia": "en.am#holiday@group.v.calendar.google.com",
  "AW Aruba": "en.aw#holiday@group.v.calendar.google.com",
  "AU Australia": "en.australian#holiday@group.v.calendar.google.com",
  "AT Austria": "en.austrian#holiday@group.v.calendar.google.com",
  "AZ Azerbaijan": "en.az#holiday@group.v.calendar.google.com",
  "BS Bahamas": "en.bs#holiday@group.v.calendar.google.com",
  "BH Bahrain": "en.bh#holiday@group.v.calendar.google.com",
  "BD Bangladesh": "en.bd#holiday@group.v.calendar.google.com",
  "BB Barbados": "en.bb#holiday@group.v.calendar.google.com",
  "BY Belarus": "en.by#holiday@group.v.calendar.google.com",
  "BE Belgium": "en.be#holiday@group.v.calendar.google.com",
  "BZ Belize": "en.bz#holiday@group.v.calendar.google.com",
  "BJ Benin": "en.bj#holiday@group.v.calendar.google.com",
  "BM Bermuda": "en.bm#holiday@group.v.calendar.google.com",
  "BT Bhutan": "en.bt#holiday@group.v.calendar.google.com",
  "BO Bolivia": "en.bo#holiday@group.v.calendar.google.com",
  "BA Bosnia and Herzegovina": "en.ba#holiday@group.v.calendar.google.com",
  "BW Botswana": "en.bw#holiday@group.v.calendar.google.com",
  "BR Brazil": "en.brazilian#holiday@group.v.calendar.google.com",
  "VG British Virgin Islands": "en.vg#holiday@group.v.calendar.google.com",
  "BN Brunei Darussalam": "en.bn#holiday@group.v.calendar.google.com",
  "BG Bulgaria": "en.bulgarian#holiday@group.v.calendar.google.com",
  "BF Burkina Faso": "en.bf#holiday@group.v.calendar.google.com",
  "BI Burundi": "en.bi#holiday@group.v.calendar.google.com",
  "KH Cambodia": "en.kh#holiday@group.v.calendar.google.com",
  "CM Cameroon": "en.cm#holiday@group.v.calendar.google.com",
  "CA Canada": "en.canadian#holiday@group.v.calendar.google.com",
  "CV Cape Verde": "en.cv#holiday@group.v.calendar.google.com",
  "KY Cayman Islands": "en.ky#holiday@group.v.calendar.google.com",
  "CF Central African Republic": "en.cf#holiday@group.v.calendar.google.com",
  "TD Chad": "en.td#holiday@group.v.calendar.google.com",
  "CL Chile": "en.cl#holiday@group.v.calendar.google.com",
  "CN China": "en.china#holiday@group.v.calendar.google.com",
  "CO Colombia": "en.co#holiday@group.v.calendar.google.com",
  "KM Comoros": "en.km#holiday@group.v.calendar.google.com",
  "CG Congo": "en.cg#holiday@group.v.calendar.google.com",
  "CK Cook Islands": "en.ck#holiday@group.v.calendar.google.com",
  "CR Costa Rica": "en.cr#holiday@group.v.calendar.google.com",
  "CI Côte d'Ivoire": "en.ci#holiday@group.v.calendar.google.com",
  "HR Croatia": "en.croatian#holiday@group.v.calendar.google.com",
  "CU Cuba": "en.cu#holiday@group.v.calendar.google.com",
  "CW Curaçao": "en.cw#holiday@group.v.calendar.google.com",
  "CY Cyprus": "en.cy#holiday@group.v.calendar.google.com",
  "CZ Czechia": "en.czech#holiday@group.v.calendar.google.com",
  "KP Democratic People's Republic of Korea":
    "en.kp#holiday@group.v.calendar.google.com",
  "DK Denmark": "en.danish#holiday@group.v.calendar.google.com",
  "DJ Djibouti": "en.dj#holiday@group.v.calendar.google.com",
  "DM Dominica": "en.dm#holiday@group.v.calendar.google.com",
  "DO Dominican Republic": "en.do#holiday@group.v.calendar.google.com",
  "EC Ecuador": "en.ec#holiday@group.v.calendar.google.com",
  "EG Egypt": "en.eg#holiday@group.v.calendar.google.com",
  "SV El Salvador": "en.sv#holiday@group.v.calendar.google.com",
  "GQ Equatorial Guinea": "en.gq#holiday@group.v.calendar.google.com",
  "ER Eritrea": "en.er#holiday@group.v.calendar.google.com",
  "EE Estonia": "en.ee#holiday@group.v.calendar.google.com",
  "ET Ethiopia": "en.et#holiday@group.v.calendar.google.com",
  "FK Falkland Islands (Malvinas)": "en.fk#holiday@group.v.calendar.google.com",
  "FO Faroe Islands": "en.fo#holiday@group.v.calendar.google.com",
  "FM Federated States of Micronesia":
    "en.fm#holiday@group.v.calendar.google.com",
  "FJ Fiji": "en.fj#holiday@group.v.calendar.google.com",
  "FI Finland": "en.finnish#holiday@group.v.calendar.google.com",
  "FR France": "en.french#holiday@group.v.calendar.google.com",
  "GF French Guiana": "en.gf#holiday@group.v.calendar.google.com",
  "PF French Polynesia": "en.pf#holiday@group.v.calendar.google.com",
  "GA Gabon": "en.ga#holiday@group.v.calendar.google.com",
  "GM Gambia": "en.gm#holiday@group.v.calendar.google.com",
  "GE Georgia": "en.ge#holiday@group.v.calendar.google.com",
  "DE Germany": "en.german#holiday@group.v.calendar.google.com",
  "GH Ghana": "en.gh#holiday@group.v.calendar.google.com",
  "GI Gibraltar": "en.gi#holiday@group.v.calendar.google.com",
  "GR Greece": "en.greek#holiday@group.v.calendar.google.com",
  "GL Greenland": "en.gl#holiday@group.v.calendar.google.com",
  "GD Grenada": "en.gd#holiday@group.v.calendar.google.com",
  "GU Guam": "en.gu#holiday@group.v.calendar.google.com",
  "GT Guatemala": "en.gt#holiday@group.v.calendar.google.com",
  "GG Guernsey": "en.gg#holiday@group.v.calendar.google.com",
  "GN Guinea": "en.gn#holiday@group.v.calendar.google.com",
  "GW Guinea-Bissau": "en.gw#holiday@group.v.calendar.google.com",
  "GY Guyana": "en.gy#holiday@group.v.calendar.google.com",
  "HT Haiti": "en.ht#holiday@group.v.calendar.google.com",
  "VA Holy See (Vatican City State)":
    "en.va#holiday@group.v.calendar.google.com",
  "HN Honduras": "en.hn#holiday@group.v.calendar.google.com",
  "HK Hong Kong": "en.hong_kong#holiday@group.v.calendar.google.com",
  "HU Hungary": "en.hungarian#holiday@group.v.calendar.google.com",
  "IS Iceland": "en.is#holiday@group.v.calendar.google.com",
  "IN India": "en.indian#holiday@group.v.calendar.google.com",
  "ID Indonesia": "en.indonesian#holiday@group.v.calendar.google.com",
  "IQ Iraq": "en.iq#holiday@group.v.calendar.google.com",
  "IE Ireland": "en.irish#holiday@group.v.calendar.google.com",
  "IR Islamic Republic of Iran": "en.ir#holiday@group.v.calendar.google.com",
  "IM Isle of Man": "en.im#holiday@group.v.calendar.google.com",
  "IL Israel": "en.jewish#holiday@group.v.calendar.google.com",
  "IT Italy": "en.italian#holiday@group.v.calendar.google.com",
  "JM Jamaica": "en.jm#holiday@group.v.calendar.google.com",
  "JP Japan": "en.japanese#holiday@group.v.calendar.google.com",
  "JE Jersey": "en.je#holiday@group.v.calendar.google.com",
  "JO Jordan": "en.jo#holiday@group.v.calendar.google.com",
  "KZ Kazakhstan": "en.kz#holiday@group.v.calendar.google.com",
  "KE Kenya": "en.ke#holiday@group.v.calendar.google.com",
  "KI Kiribati": "en.ki#holiday@group.v.calendar.google.com",
  "KW Kuwait": "en.kw#holiday@group.v.calendar.google.com",
  "KG Kyrgyzstan": "en.kg#holiday@group.v.calendar.google.com",
  "LA Lao People's Democratic Republic":
    "en.la#holiday@group.v.calendar.google.com",
  "LV Latvia": "en.latvian#holiday@group.v.calendar.google.com",
  "LB Lebanon": "en.lb#holiday@group.v.calendar.google.com",
  "LS Lesotho": "en.ls#holiday@group.v.calendar.google.com",
  "LR Liberia": "en.lr#holiday@group.v.calendar.google.com",
  "LY Libya": "en.ly#holiday@group.v.calendar.google.com",
  "LI Liechtenstein": "en.li#holiday@group.v.calendar.google.com",
  "LT Lithuania": "en.lithuanian#holiday@group.v.calendar.google.com",
  "LU Luxembourg": "en.lu#holiday@group.v.calendar.google.com",
  "MO Macao": "en.mo#holiday@group.v.calendar.google.com",
  "MG Madagascar": "en.mg#holiday@group.v.calendar.google.com",
  "MW Malawi": "en.mw#holiday@group.v.calendar.google.com",
  "MY Malaysia": "en.malaysia#holiday@group.v.calendar.google.com",
  "MV Maldives": "en.mv#holiday@group.v.calendar.google.com",
  "ML Mali": "en.ml#holiday@group.v.calendar.google.com",
  "MT Malta": "en.mt#holiday@group.v.calendar.google.com",
  "MH Marshall Islands": "en.mh#holiday@group.v.calendar.google.com",
  "MQ Martinique": "en.mq#holiday@group.v.calendar.google.com",
  "MR Mauritania": "en.mr#holiday@group.v.calendar.google.com",
  "MU Mauritius": "en.mu#holiday@group.v.calendar.google.com",
  "YT Mayotte": "en.yt#holiday@group.v.calendar.google.com",
  "MX Mexico": "en.mexican#holiday@group.v.calendar.google.com",
  "MD Moldova": "en.md#holiday@group.v.calendar.google.com",
  "MC Monaco": "en.mc#holiday@group.v.calendar.google.com",
  "MN Mongolia": "en.mn#holiday@group.v.calendar.google.com",
  "ME Montenegro": "en.me#holiday@group.v.calendar.google.com",
  "MS Montserrat": "en.ms#holiday@group.v.calendar.google.com",
  "MA Morocco": "en.ma#holiday@group.v.calendar.google.com",
  "MZ Mozambique": "en.mz#holiday@group.v.calendar.google.com",
  "MM Myanmar": "en.mm#holiday@group.v.calendar.google.com",
  "NA Namibia": "en.na#holiday@group.v.calendar.google.com",
  "NR Nauru": "en.nr#holiday@group.v.calendar.google.com",
  "NP Nepal": "en.np#holiday@group.v.calendar.google.com",
  "NL Netherlands": "en.dutch#holiday@group.v.calendar.google.com",
  "NC New Caledonia": "en.nc#holiday@group.v.calendar.google.com",
  "NZ New Zealand": "en.new_zealand#holiday@group.v.calendar.google.com",
  "NI Nicaragua": "en.ni#holiday@group.v.calendar.google.com",
  "NE Niger": "en.ne#holiday@group.v.calendar.google.com",
  "NG Nigeria": "en.ng#holiday@group.v.calendar.google.com",
  "MP Northern Mariana Islands": "en.mp#holiday@group.v.calendar.google.com",
  "NO Norway": "en.norwegian#holiday@group.v.calendar.google.com",
  "OM Oman": "en.om#holiday@group.v.calendar.google.com",
  "PK Pakistan": "en.pk#holiday@group.v.calendar.google.com",
  "PW Palau": "en.pw#holiday@group.v.calendar.google.com",
  "PA Panama": "en.pa#holiday@group.v.calendar.google.com",
  "PG Papua New Guinea": "en.pg#holiday@group.v.calendar.google.com",
  "PY Paraguay": "en.py#holiday@group.v.calendar.google.com",
  "PE Peru": "en.pe#holiday@group.v.calendar.google.com",
  "PH Philippines": "en.philippines#holiday@group.v.calendar.google.com",
  "PL Poland": "en.polish#holiday@group.v.calendar.google.com",
  "PT Portugal": "en.portuguese#holiday@group.v.calendar.google.com",
  "PR Puerto Rico": "en.pr#holiday@group.v.calendar.google.com",
  "QA Qatar": "en.qa#holiday@group.v.calendar.google.com",
  "KR Republic of Korea": "en.south_korea#holiday@group.v.calendar.google.com",
  "RE Réunion": "en.re#holiday@group.v.calendar.google.com",
  "RO Romania": "en.ro#holiday@group.v.calendar.google.com",
  "RU Russian Federation": "en.ru#holiday@group.v.calendar.google.com",
  "RW Rwanda": "en.rw#holiday@group.v.calendar.google.com",
  "BL Saint Barthélemy": "en.bl#holiday@group.v.calendar.google.com",
  "SH Saint Helena, Ascension and Tristan da Cunha":
    "en.sh#holiday@group.v.calendar.google.com",
  "KN Saint Kitts and Nevis": "en.kn#holiday@group.v.calendar.google.com",
  "LC Saint Lucia": "en.lc#holiday@group.v.calendar.google.com",
  "MF Saint Martin (French part)": "en.mf#holiday@group.v.calendar.google.com",
  "PM Saint Pierre and Miquelon": "en.pm#holiday@group.v.calendar.google.com",
  "VC Saint Vincent and the Grenadines":
    "en.vc#holiday@group.v.calendar.google.com",
  "WS Samoa": "en.ws#holiday@group.v.calendar.google.com",
  "SM San Marino": "en.sm#holiday@group.v.calendar.google.com",
  "ST São Tomé and Príncipe": "en.st#holiday@group.v.calendar.google.com",
  "SA Saudi Arabia": "en.sa#holiday@group.v.calendar.google.com",
  "SN Senegal": "en.sn#holiday@group.v.calendar.google.com",
  "RS Serbia": "en.rs#holiday@group.v.calendar.google.com",
  "SC Seychelles": "en.sc#holiday@group.v.calendar.google.com",
  "SL Sierra Leone": "en.sl#holiday@group.v.calendar.google.com",
  "SG Singapore": "en.sg#holiday@group.v.calendar.google.com",
  "SX Sint Maarten": "en.sx#holiday@group.v.calendar.google.com",
  "SK Slovakia": "en.sk#holiday@group.v.calendar.google.com",
  "SI Slovenia": "en.si#holiday@group.v.calendar.google.com",
  "SB Solomon Islands": "en.sb#holiday@group.v.calendar.google.com",
  "SO Somalia": "en.so#holiday@group.v.calendar.google.com",
  "ZA South Africa": "en.za#holiday@group.v.calendar.google.com",
  "GS South Georgia and the South Sandwich Islands":
    "en.gs#holiday@group.v.calendar.google.com",
  "ES Spain": "en.spanish#holiday@group.v.calendar.google.com",
  "LK Sri Lanka": "en.lk#holiday@group.v.calendar.google.com",
  "SD Sudan": "en.sd#holiday@group.v.calendar.google.com",
  "SR Suriname": "en.sr#holiday@group.v.calendar.google.com",
  "SJ Svalbard and Jan Mayen": "en.sj#holiday@group.v.calendar.google.com",
  "SE Sweden": "en.swedish#holiday@group.v.calendar.google.com",
  "CH Switzerland": "en.ch#holiday@group.v.calendar.google.com",
  "SY Syrian Arab Republic": "en.sy#holiday@group.v.calendar.google.com",
  "TW Taiwan": "en.tw#holiday@group.v.calendar.google.com",
  "TJ Tajikistan": "en.tj#holiday@group.v.calendar.google.com",
  "TZ Tanzania": "en.tz#holiday@group.v.calendar.google.com",
  "TH Thailand": "en.th#holiday@group.v.calendar.google.com",
  "TL Timor-Leste": "en.tl#holiday@group.v.calendar.google.com",
  "TG Togo": "en.tg#holiday@group.v.calendar.google.com",
  "TK Tokelau": "en.tk#holiday@group.v.calendar.google.com",
  "TO Tonga": "en.to#holiday@group.v.calendar.google.com",
  "TT Trinidad and Tobago": "en.tt#holiday@group.v.calendar.google.com",
  "TN Tunisia": "en.tn#holiday@group.v.calendar.google.com",
  "TR Turkey": "en.tr#holiday@group.v.calendar.google.com",
  "TM Turkmenistan": "en.tm#holiday@group.v.calendar.google.com",
  "TC Turks and Caicos Islands": "en.tc#holiday@group.v.calendar.google.com",
  "TV Tuvalu": "en.tv#holiday@group.v.calendar.google.com",
  "UG Uganda": "en.ug#holiday@group.v.calendar.google.com",
  "UA Ukraine": "en.ua#holiday@group.v.calendar.google.com",
  "AE United Arab Emirates": "en.ae#holiday@group.v.calendar.google.com",
  "GB United Kingdom": "en.gb#holiday@group.v.calendar.google.com",
  "US United States": "en.us#holiday@group.v.calendar.google.com",
  "UY Uruguay": "en.uy#holiday@group.v.calendar.google.com",
  "UZ Uzbekistan": "en.uz#holiday@group.v.calendar.google.com",
  "VU Vanuatu": "en.vu#holiday@group.v.calendar.google.com",
  "VE Venezuela (Bolivarian Republic of)":
    "en.ve#holiday@group.v.calendar.google.com",
  "VN Viet Nam": "en.vn#holiday@group.v.calendar.google.com",
  "WF Wallis and Futuna": "en.wf#holiday@group.v.calendar.google.com",
  "YE Yemen": "en.ye#holiday@group.v.calendar.google.com",
  "ZM Zambia": "en.zm#holiday@group.v.calendar.google.com",
  "ZW Zimbabwe": "en.zw#holiday@group.v.calendar.google.com",
};
